namespace Universe.PrototypingSources
{
    using System.Collections.Generic;

    class SourceOfNames
    {
        public static List<HumanName> Names = new List<HumanName>(new HumanName[]
        {
            // Male Names: 522
            new HumanName("Jack", 5, Gender.Male, "The English name is a pet form of John."),
            new HumanName("Jacob", 5, Gender.Male, "Biblical name from the Hebrew name Yaakov."),
            new HumanName("Jake", 5, Gender.Male, "English name derived from Jack."),
            new HumanName("James", 5, Gender.Male, "Biblical name from the Latin name Iacomus."),
            new HumanName("Jamie", 5, Gender.Male, "A pet name for James"),
            new HumanName("John", 5, Gender.Male, "Anglicised version of Ioannes."),
            new HumanName("Leo", 5, Gender.Male, "Leo means a lion."),
            new HumanName("Lucas", 5, Gender.Male, "A form of Luke."),
            new HumanName("Luke", 5, Gender.Male, "Luke from name Loukas."),
            new HumanName("Mason", 5, Gender.Male, "Someone who works with stone"),
            new HumanName("Matthew", 5, Gender.Male, "Biblical name meaning ‘gift of god’"),
            new HumanName("Max", 5, Gender.Male, "Short form the name Maxwell"),
            new HumanName("Noah", 5, Gender.Male, "Biblical name possibly means ‘rest’"),
            new HumanName("Oliver", 5, Gender.Male, "English male name derived from the olive tree"),
            new HumanName("Riley", 5, Gender.Male, "Means rye meadow"),
            new HumanName("Ryan", 5, Gender.Male, "Origin unknown"),
            new HumanName("Samuel", 5, Gender.Male, "Biblical name from Shemuel"),
            new HumanName("Sebastian", 5, Gender.Male, "Man from the place Sebasta"),
            new HumanName("Theo", 5, Gender.Male, "Pet name for Theodore"),
            new HumanName("Theo", 5, Gender.Male, "Pet name for Theodore"),
            new HumanName("Toby", 5, Gender.Male, "English form of Tobias"),
            new HumanName("Tyler", 5, Gender.Male, "Occupation of someone who tiled the roofs"),
            new HumanName("Will", 5, Gender.Male, "Short form William"),
            new HumanName("William", 5, Gender.Male, "Common Germanic name meaning determined Protection"),
            new HumanName("Zachary", 5, Gender.Male, "From the name Zachariah"),
            new HumanName("Alex", 4, Gender.Male, "Short name for Alexander"),
            new HumanName("Alexander", 4, Gender.Male, "From the name Alexandros"),
            new HumanName("Alfie", 4, Gender.Male, "Pet form of the English name Alfred"),
            new HumanName("Andrew", 4, Gender.Male, "English form of Andreas"),
            new HumanName("Benjamin", 4, Gender.Male, "Biblical origin"),
            new HumanName("Bill", 4, Gender.Male, "Pet name of William"),
            new HumanName("Charles", 4, Gender.Male, "Means ‘free man’ orginates from the names Cearl or Ceorl"),
            new HumanName("Daniel", 4, Gender.Male, "Means God is my Judge in Hebrew"),
            new HumanName("Dexter", 4, Gender.Male, "From the occupation dyer"),
            new HumanName("Elliot", 4, Gender.Male, "Version of Elias"),
            new HumanName("Jenson", 4, Gender.Male, "Means son of Jens."),
            new HumanName("Joe", 4, Gender.Male, "Short for Joseph."),
            new HumanName("Joey", 4, Gender.Male, "Pet form of Joe."),
            new HumanName("Joseph", 4, Gender.Male, "From Yosef meaning God will make you fertile."),
            new HumanName("Josh", 4, Gender.Male, "Pet form of Joshua."),
            new HumanName("Jude", 4, Gender.Male, "Jude from the name Judas."),
            new HumanName("Leon", 4, Gender.Male, "A form of Leo."),
            new HumanName("Louie", 4, Gender.Male, "A variant of Louis."),
            new HumanName("Michael", 4, Gender.Male, "Biblical name that means like God"),
            new HumanName("Ollie", 4, Gender.Male, "Pet name for Oliver"),
            new HumanName("Oscar", 4, Gender.Male, "Means deers’ friend"),
            new HumanName("Peter", 4, Gender.Male, "Popular biblical name from the name Petros"),
            new HumanName("Richard", 4, Gender.Male, "Means powerful and brave"),
            new HumanName("Robert", 4, Gender.Male, "English name means bright or famous fame"),
            new HumanName("Ronnie", 4, Gender.Male, "Short form of the name Ronald"),
            new HumanName("Simon", 4, Gender.Male, "English male name from Simeon"),
            new HumanName("Stanley", 4, Gender.Male, "From the place names in England"),
            new HumanName("Taylor", 4, Gender.Male, "Name from a person with the occupation of a tailor"),
            new HumanName("Tommy", 4, Gender.Male, "Pet form of Thomas"),
            new HumanName("Willard", 4, Gender.Male, "Means desire and brave"),
            new HumanName("Zach", 4, Gender.Male, "Short name for Zachary"),
            new HumanName("Adrian", 3, Gender.Male, "From the Latin Name Hadrianus"),
            new HumanName("Al", 3, Gender.Male, "Pet name from name starting with the letter Al"),
            new HumanName("Albert", 3, Gender.Male, "Derived form the words meaning Noble and Bright"),
            new HumanName("Alec", 3, Gender.Male, "Short name for Alexander"),
            new HumanName("Alf", 3, Gender.Male, "Pet form of the English name Alfred"),
            new HumanName("Alfred", 3, Gender.Male, "It means supernaturally and wise"),
            new HumanName("Andy", 3, Gender.Male, "Pet form of Andrew"),
            new HumanName("Anthony", 3, Gender.Male, "From the Roman family name Antonius"),
            new HumanName("Austin", 3, Gender.Male, "From the Latin name Augustinus"),
            new HumanName("Blake", 3, Gender.Male, "A person with hair or skin either Fair or Dark"),
            new HumanName("Bob", 3, Gender.Male, "Pet for of Robert"),
            new HumanName("Bradley", 3, Gender.Male, "from the Broad Clearing"),
            new HumanName("Brian", 3, Gender.Male, "Means high and noble"),
            new HumanName("Carl", 3, Gender.Male, "From the German boy’s name Karl"),
            new HumanName("Charlie", 3, Gender.Male, "Pet form of Charles"),
            new HumanName("Charlton", 3, Gender.Male, "Made popular by Charlton Heston. Old English name Ceorlatun"),
            new HumanName("Chris", 3, Gender.Male, "Pet form of the name Christopher"),
            new HumanName("Christopher", 3, Gender.Male, "From the Greek name Khristophoros and means ‘Christ Bearer’"),
            new HumanName("Colin", 3, Gender.Male, "Short form of Nicholas"),
            new HumanName("Craig", 3, Gender.Male, "Means rocky from the Gaelic word creag"),
            new HumanName("Darell", 3, Gender.Male, "From the surname d’Airelle"),
            new HumanName("Dean", 3, Gender.Male, "Someone who lived in a valley"),
            new HumanName("Derek", 3, Gender.Male, "Related to the German name Theodoric"),
            new HumanName("Douglas", 3, Gender.Male, "Meaning black river"),
            new HumanName("Ed", 3, Gender.Male, "Pet form of Edward"),
            new HumanName("Jackson", 3, Gender.Male, "Jackson means the son of Jack."),
            new HumanName("Jason", 3, Gender.Male, "From Greek mythology Iason."),
            new HumanName("Jeffrey", 3, Gender.Male, "English name from Geoffrey"),
            new HumanName("Jeremy", 3, Gender.Male, "English version of Jeremiah."),
            new HumanName("Jim", 3, Gender.Male, "Pet form of the English boy’s name James."),
            new HumanName("Johnny", 3, Gender.Male, "Pet form of John."),
            new HumanName("Jordan", 3, Gender.Male, "Jordan from the river Jordan."),
            new HumanName("Julian", 3, Gender.Male, "English version of yhe name Julius."),
            new HumanName("Justin", 3, Gender.Male, "English version of the name Justus."),
            new HumanName("Keith", 3, Gender.Male, "English name from the place in East Lothian."),
            new HumanName("Ken", 3, Gender.Male, "Pet form of Kenneth."),
            new HumanName("Kerry", 3, Gender.Male, "From the Irish county of Kerry."),
            new HumanName("Kevin", 3, Gender.Male, "From Gaelic name Caimhin."),
            new HumanName("Lance", 3, Gender.Male, "Lance from the weapon a lance."),
            new HumanName("Larry", 3, Gender.Male, "Pet form of Lawrence."),
            new HumanName("Lee", 3, Gender.Male, "Means wood or clearing."),
            new HumanName("Len", 3, Gender.Male, "Len is short for Leonard."),
            new HumanName("Lonnie", 3, Gender.Male, "Origin unknown."),
            new HumanName("Malcolm", 3, Gender.Male, "Means ‘dovotee of St Columba’"),
            new HumanName("Mark", 3, Gender.Male, "From the name Marcus"),
            new HumanName("Martin", 3, Gender.Male, "From the Roman god of War"),
            new HumanName("Matt", 3, Gender.Male, "Pet from of Matthew"),
            new HumanName("Mike", 3, Gender.Male, "Pet name for Michael"),
            new HumanName("Neil", 3, Gender.Male, "From Gaelic name Niall"),
            new HumanName("Nicholas", 3, Gender.Male, "Means peoples’ victory"),
            new HumanName("Patrick", 3, Gender.Male, "Patron St. Of Ireland"),
            new HumanName("Paul", 3, Gender.Male, "From Paulus meaning Small"),
            new HumanName("Percy", 3, Gender.Male, "Pet form of Percival"),
            new HumanName("Perry", 3, Gender.Male, "Someone who lived by a pear tree"),
            new HumanName("Phil", 3, Gender.Male, "Short form of Philip"),
            new HumanName("Philip", 3, Gender.Male, "From a person who loves horses"),
            new HumanName("Rich", 3, Gender.Male, "Pet form of Richard"),
            new HumanName("Richie", 3, Gender.Male, "Pet form of Richard"),
            new HumanName("Roger", 3, Gender.Male, "English boy’s name meaning famous spear"),
            new HumanName("Roland", 3, Gender.Male, "English name meaning famous land"),
            new HumanName("Roy", 3, Gender.Male, "Nickname of someone with red hair"),
            new HumanName("Scott", 3, Gender.Male, "Someone from Scotland"),
            new HumanName("Timothy", 3, Gender.Male, "Means god’s honour"),
            new HumanName("Tom", 3, Gender.Male, "Pet form of Thomas"),
            new HumanName("Ainsley", 2, Gender.Male, "Likely from the place names Annesley or Ansley"),
            new HumanName("Alan", 2, Gender.Male, "Of Celtic origins"),
            new HumanName("Alexis", 2, Gender.Male, "From the name Alexius"),
            new HumanName("Allan", 2, Gender.Male, "Varient of Alan"),
            new HumanName("Allen", 2, Gender.Male, "Varient of Alan"),
            new HumanName("Alton", 2, Gender.Male, "From a town in England"),
            new HumanName("Alvin", 2, Gender.Male, "Derived from the words meaning Supernatural + Friend"),
            new HumanName("Armstrong", 2, Gender.Male, "Possibly orginated from a person with Strong Arms"),
            new HumanName("Arnold", 2, Gender.Male, "From the words meaning Eagle and Ruler"),
            new HumanName("Ashley", 2, Gender.Male, "Name comes from the tree Ash"),
            new HumanName("Aubrey", 2, Gender.Male, "English name meaning Supernatural Power"),
            new HumanName("Baldwin", 2, Gender.Male, "Means brave friend"),
            new HumanName("Basil", 2, Gender.Male, "Meaning Royal"),
            new HumanName("Baz", 2, Gender.Male, "Pet form of Barry"),
            new HumanName("Bernard", 2, Gender.Male, "Means strong/brave bear"),
            new HumanName("Bert", 2, Gender.Male, "Pet name for Albert"),
            new HumanName("Bobby", 2, Gender.Male, "Pet for of Robert"),
            new HumanName("Brad", 2, Gender.Male, "Short for the name Brafley or Bradford"),
            new HumanName("Brent", 2, Gender.Male, "From the Steep Hill in Dorset and Summerset"),
            new HumanName("Brooke", 2, Gender.Male, "After a small stream"),
            new HumanName("Bruce", 2, Gender.Male, "From the Scottish surname"),
            new HumanName("Bryant", 2, Gender.Male, "Comes from the English boy’s name Brian"),
            new HumanName("Burton", 2, Gender.Male, "After place names in England with a Fortress"),
            new HumanName("Carter", 2, Gender.Male, "Name comes from a person who drives a cart"),
            new HumanName("Carver", 2, Gender.Male, "Name comes from a person with a trade as a wood carver"),
            new HumanName("Casey", 2, Gender.Male, "From the brave hero Casey Jones who’s name originates from his birthplace Cayce"),
            new HumanName("Cecil", 2, Gender.Male, "From a Welsh Celtic name Seissylt"),
            new HumanName("Chandler", 2, Gender.Male, "Originates from a person who made candles"),
            new HumanName("Chapman", 2, Gender.Male, "Middle ages name that means Merchant"),
            new HumanName("Chester", 2, Gender.Male, "From people who came from the English place Chester"),
            new HumanName("Christian", 2, Gender.Male, "From the name Chrisianus which means a Christian"),
            new HumanName("Chuck", 2, Gender.Male, "Mainly US based term of endearment"),
            new HumanName("Clarence", 2, Gender.Male, "Linked to famous royal princes"),
            new HumanName("Claude", 2, Gender.Male, "From the Latin name Claudius meaning ‘Lame’"),
            new HumanName("Cliff", 2, Gender.Male, "Short form of Clifford"),
            new HumanName("Clifton", 2, Gender.Male, "Related to the words cliff, slop and riverbank"),
            new HumanName("Clive", 2, Gender.Male, "Found in various English locations – meaning clif or slope"),
            new HumanName("Clyde", 2, Gender.Male, "From the Scottish river"),
            new HumanName("Courtney", 2, Gender.Male, "Originates from places in northen France"),
            new HumanName("Cuthbert", 2, Gender.Male, "Middle English boy’s name meaning famous and bright"),
            new HumanName("Cyril", 2, Gender.Male, "Lord like from Greek name Kyrillos"),
            new HumanName("Dalton", 2, Gender.Male, "A person from a valley town"),
            new HumanName("Damian", 2, Gender.Male, "From the Greek name Damianos"),
            new HumanName("Danny", 2, Gender.Male, "A pet form of Daniel"),
            new HumanName("Darcy", 2, Gender.Male, "From the surname d’Arcy"),
            new HumanName("Darren", 2, Gender.Male, "Origin unknown"),
            new HumanName("Davy", 2, Gender.Male, "Pet form of David"),
            new HumanName("Del", 2, Gender.Male, "Pet form of Derek"),
            new HumanName("Den", 2, Gender.Male, "An English name short for Dennis"),
            new HumanName("Dennis", 2, Gender.Male, "From Greek name Dionysios"),
            new HumanName("Denzil", 2, Gender.Male, "After the place Denzell in Cornwall"),
            new HumanName("Derick", 2, Gender.Male, "Another spelling of the name Derek"),
            new HumanName("Des", 2, Gender.Male, "Short for Desmond"),
            new HumanName("Dominic", 2, Gender.Male, "From the Latain name that means Lord"),
            new HumanName("Donald", 2, Gender.Male, "From Galic name Domhnall"),
            new HumanName("Doug", 2, Gender.Male, "English name short for Dougless"),
            new HumanName("Dustin", 2, Gender.Male, "Origin unknown"),
            new HumanName("Dwayne", 2, Gender.Male, "Originates from the name Duane"),
            new HumanName("Eddie", 2, Gender.Male, "Pet form of Edward"),
            new HumanName("Edmond", 2, Gender.Male, "Old English name meaning prosperous protector"),
            new HumanName("Edric", 2, Gender.Male, "The name means rich and powerful"),
            new HumanName("Eliot", 2, Gender.Male, "Version of Elias (see also Elliot)"),
            new HumanName("Ellis", 2, Gender.Male, "From the name Elias"),
            new HumanName("Eric", 2, Gender.Male, "Means always a ruler"),
            new HumanName("Jackie", 2, Gender.Male, "Pet form of Jack."),
            new HumanName("Jarvis", 2, Gender.Male, "English name from the Norman name Gervaise."),
            new HumanName("Jasper", 2, Gender.Male, "A bearer of treasure (as in the 3 wise men)"),
            new HumanName("Jeff", 2, Gender.Male, "Pet form of Jeffrey."),
            new HumanName("Jermaine", 2, Gender.Male, "Male name from Germaine."),
            new HumanName("Jerome", 2, Gender.Male, "means holy name."),
            new HumanName("Jerrard", 2, Gender.Male, "Jerrard from the name Gerard."),
            new HumanName("Jerry", 2, Gender.Male, "Pet form of Jeremy."),
            new HumanName("Jimmy", 2, Gender.Male, "Jimmy from Jim."),
            new HumanName("Kelly", 2, Gender.Male, "Kelly is  an English boy’s name for Ceallagh."),
            new HumanName("Kelvin", 2, Gender.Male, "From the river that branches into the Clyde."),
            new HumanName("Kendrick", 2, Gender.Male, "Origin unknown."),
            new HumanName("Kenelm", 2, Gender.Male, "Means bold helmet protector."),
            new HumanName("Kennard", 2, Gender.Male, "Kennard from the middle ages- could mean royal guard."),
            new HumanName("Kenneth", 2, Gender.Male, "From the Gaelic names Cinaed and Cainnech."),
            new HumanName("Kent", 2, Gender.Male, "Someone from Kent in England."),
            new HumanName("Kit", 2, Gender.Male, "Pet name of Christopher."),
            new HumanName("Lacey", 2, Gender.Male, "People from Lassy in France."),
            new HumanName("Lambert", 2, Gender.Male, "Lambert means famous land."),
            new HumanName("Lancelot", 2, Gender.Male, "Celtic origin."),
            new HumanName("Laurel", 2, Gender.Male, "Meaning a tree."),
            new HumanName("Laurence", 2, Gender.Male, "A person from Laurentius."),
            new HumanName("Lawrence", 2, Gender.Male, "Anglicised form of Laurance."),
            new HumanName("Leighton", 2, Gender.Male, "Means leek settlement."),
            new HumanName("Lennard", 2, Gender.Male, "English spelling of Leonard."),
            new HumanName("Lenny", 2, Gender.Male, "Variation of Lenny."),
            new HumanName("Leonard", 2, Gender.Male, "Meaning lion."),
            new HumanName("Leopold", 2, Gender.Male, "Meaning brave people."),
            new HumanName("Leroy", 2, Gender.Male, "Means the king."),
            new HumanName("Les", 2, Gender.Male, "Short for Lesley"),
            new HumanName("Lesley", 2, Gender.Male, "Lesley name variant of Leslie"),
            new HumanName("Lex", 2, Gender.Male, "Pet name for Alex."),
            new HumanName("Lindon", 2, Gender.Male, "Variation of Lindon."),
            new HumanName("Lionel", 2, Gender.Male, "From the name Leon."),
            new HumanName("Lovell", 2, Gender.Male, "Means club wolf."),
            new HumanName("Ludo", 2, Gender.Male, "Pet form of Ludovic."),
            new HumanName("Lyle", 2, Gender.Male, "Someone who live on an island."),
            new HumanName("Lyndon", 2, Gender.Male, "A place in Leicestershire."),
            new HumanName("Marlon", 2, Gender.Male, "Made famous by Marlon Brando"),
            new HumanName("Marvin", 2, Gender.Male, "From Mervyn"),
            new HumanName("Maxwell", 2, Gender.Male, "After the place name on the river Tweed"),
            new HumanName("Mel", 2, Gender.Male, "Short for Melvin"),
            new HumanName("Melville", 2, Gender.Male, "Means bad settlement"),
            new HumanName("Melvin", 2, Gender.Male, "Origin unknown."),
            new HumanName("Merlin", 2, Gender.Male, "From the Welsh name Myrddin"),
            new HumanName("Mick", 2, Gender.Male, "Pet name for Michael"),
            new HumanName("Milburn", 2, Gender.Male, "A place name"),
            new HumanName("Miles", 2, Gender.Male, "Origin unknown."),
            new HumanName("Milton", 2, Gender.Male, "Settlement with a miill"),
            new HumanName("Montgomery", 2, Gender.Male, "Places names in Calvdos"),
            new HumanName("Monty", 2, Gender.Male, "Pet for of Montgomery"),
            new HumanName("Morris", 2, Gender.Male, "From Maurice"),
            new HumanName("Ned", 2, Gender.Male, "Pet form of Edward"),
            new HumanName("Neville", 2, Gender.Male, "New settlement"),
            new HumanName("Nigel", 2, Gender.Male, "Means black"),
            new HumanName("Norman", 2, Gender.Male, "Means a man from the North"),
            new HumanName("Norris", 2, Gender.Male, "Means a man from the North"),
            new HumanName("Osmond", 2, Gender.Male, "Means God’s protector"),
            new HumanName("Oswald", 2, Gender.Male, "God’s rule"),
            new HumanName("Paddy", 2, Gender.Male, "Pet name for Patrick"),
            new HumanName("Pat", 2, Gender.Male, "Pet name for Patrick"),
            new HumanName("Pearce", 2, Gender.Male, "A form of Pierce"),
            new HumanName("Pierce", 2, Gender.Male, "From the name Piers"),
            new HumanName("Quinn", 2, Gender.Male, "Meaning the wise man"),
            new HumanName("Ralph", 2, Gender.Male, "Means counsel wolf"),
            new HumanName("Ray", 2, Gender.Male, "English name short for Raymond"),
            new HumanName("Raymond", 2, Gender.Male, "This name means wise protector"),
            new HumanName("Reid", 2, Gender.Male, "Someone with red hair"),
            new HumanName("Ridley", 2, Gender.Male, "Name from various places in England"),
            new HumanName("Robin", 2, Gender.Male, "Pet form of Robert"),
            new HumanName("Rocky", 2, Gender.Male, "From the name Rocco"),
            new HumanName("Roderick", 2, Gender.Male, "Means prominent ruler, of Germanic origin"),
            new HumanName("Roly", 2, Gender.Male, "Pet form of Roland"),
            new HumanName("Ronald", 2, Gender.Male, "English/Scottish name from Rognvaldr"),
            new HumanName("Ross", 2, Gender.Male, "Someone who come from the headland"),
            new HumanName("Rupert", 2, Gender.Male, "Version of the name Robert"),
            new HumanName("Russ", 2, Gender.Male, "English name short for Russell"),
            new HumanName("Russell", 2, Gender.Male, "Mean little red person"),
            new HumanName("Samson", 2, Gender.Male, "Biblical name from Shimshon"),
            new HumanName("Sandy", 2, Gender.Male, "Pet name of Alexander"),
            new HumanName("Selwyn", 2, Gender.Male, "Origin unknown"),
            new HumanName("Shane", 2, Gender.Male, "from Sean"),
            new HumanName("Shaun", 2, Gender.Male, "from Sean"),
            new HumanName("Shelley", 2, Gender.Male, "Place names in England"),
            new HumanName("Sidney", 2, Gender.Male, "A man who comes from the land"),
            new HumanName("Sinclair", 2, Gender.Male, "From Saint-Clair in Normandy"),
            new HumanName("Stacy", 2, Gender.Male, "Orgin unknown"),
            new HumanName("Stan", 2, Gender.Male, "Pet form of the name Stanley"),
            new HumanName("Stephen", 2, Gender.Male, "Derived from the Greek name Stephanos"),
            new HumanName("Stewart", 2, Gender.Male, "A steward"),
            new HumanName("Stuart", 2, Gender.Male, "A steward"),
            new HumanName("Sylvester", 2, Gender.Male, "A person from the woods"),
            new HumanName("Ted", 2, Gender.Male, "Pet form of Edward"),
            new HumanName("Terence", 2, Gender.Male, "From the Latin name Terentius"),
            new HumanName("Terry", 2, Gender.Male, "English boy’s name that means tribe power"),
            new HumanName("Thomas", 2, Gender.Male, "Thomas is a biblical name and popular in England"),
            new HumanName("Todd", 2, Gender.Male, "This English name means fox"),
            new HumanName("Tony", 2, Gender.Male, "Short version of Anthony"),
            new HumanName("Travis", 2, Gender.Male, "From someone who collects a tolls"),
            new HumanName("Tristan", 2, Gender.Male, "Form of Tristram"),
            new HumanName("Tyrone", 2, Gender.Male, "From the county in Northen Ireland"),
            new HumanName("Victor", 2, Gender.Male, "The English names means conqueror"),
            new HumanName("Vince", 2, Gender.Male, "Short form of Vincent"),
            new HumanName("Waldo", 2, Gender.Male, "Means ruler"),
            new HumanName("Walter", 2, Gender.Male, "Composed of the elements army ruler"),
            new HumanName("Wayne", 2, Gender.Male, "A person who made carts"),
            new HumanName("Webster", 2, Gender.Male, "From a person who weaves"),
            new HumanName("Winthrop", 2, Gender.Male, "Winthrop is a place name in England"),
            new HumanName("Abbott", 1, Gender.Male, "Old English name for the head of a religious community"),
            new HumanName("Abe", 1, Gender.Male, "Pet form of the name Abraham"),
            new HumanName("Addison", 1, Gender.Male, "Old English name, means son of Adam"),
            new HumanName("Aiken", 1, Gender.Male, "Old English boy’s name meaning made of oak"),
            new HumanName("Alaric", 1, Gender.Male, "Derived form the words meaning All and Ruler"),
            new HumanName("Alban", 1, Gender.Male, "An old British name. It means Scotland in Welsh."),
            new HumanName("Albion", 1, Gender.Male, "Same origins as Alban"),
            new HumanName("Aldrich", 1, Gender.Male, "Old and wise leader"),
            new HumanName("Alger", 1, Gender.Male, "It is deriver from words meaning supernaturally and spear"),
            new HumanName("Algernon", 1, Gender.Male, "From word grenon meaning moustache"),
            new HumanName("Alick", 1, Gender.Male, "Different spelling of Alec"),
            new HumanName("Ambrose", 1, Gender.Male, "From the Latin name Ambrosius- means immortal"),
            new HumanName("Archer", 1, Gender.Male, "From the man who’s job was a bowman"),
            new HumanName("Aston", 1, Gender.Male, "From the place names (meaning East settlement)"),
            new HumanName("Atwater", 1, Gender.Male, "From the words meaning Water Side"),
            new HumanName("Avery", 1, Gender.Male, "Closely associated to Alfred"),
            new HumanName("Barclay", 1, Gender.Male, "From the English place Berkeley"),
            new HumanName("Barrett", 1, Gender.Male, "From the name Baret"),
            new HumanName("Bartholomew", 1, Gender.Male, "With biblical origins"),
            new HumanName("Barton", 1, Gender.Male, "From English places meaning barley settlements"),
            new HumanName("Baxter", 1, Gender.Male, "From the name Baker"),
            new HumanName("Benedict", 1, Gender.Male, "Means Blessed"),
            new HumanName("Bennett", 1, Gender.Male, "From the name Benedict"),
            new HumanName("Benson", 1, Gender.Male, "Orginates from the name Ben"),
            new HumanName("Bentley", 1, Gender.Male, "Means grass clearing"),
            new HumanName("Berkley", 1, Gender.Male, "From the boy’s name Barclay"),
            new HumanName("Bond", 1, Gender.Male, "Means farmer"),
            new HumanName("Bret", 1, Gender.Male, "A person who comes from Brittany"),
            new HumanName("Brewster", 1, Gender.Male, "From the occupation Brewer"),
            new HumanName("Brigham", 1, Gender.Male, "Means Bridge Settler"),
            new HumanName("Bruno", 1, Gender.Male, "Means dark/brown complexion"),
            new HumanName("Buck", 1, Gender.Male, "Means male strong deer"),
            new HumanName("Bud", 1, Gender.Male, "From the term buddy"),
            new HumanName("Burgess", 1, Gender.Male, "Citizen of a town called Burgeis"),
            new HumanName("Byron", 1, Gender.Male, "Means cattle shed / or person who lives there"),
            new HumanName("Cade", 1, Gender.Male, "Means something round and lumpish"),
            new HumanName("Caesar", 1, Gender.Male, "Analgised from the Italian name Cesare"),
            new HumanName("Caldwell", 1, Gender.Male, "Means cold Well"),
            new HumanName("Calvert", 1, Gender.Male, "Means shepherd or cowboy"),
            new HumanName("Calvin", 1, Gender.Male, "From the French surname"),
            new HumanName("Carlton", 1, Gender.Male, "Places with the same origin of Charlton"),
            new HumanName("Cary", 1, Gender.Male, "From a river in Devon orSummerset"),
            new HumanName("Cassian", 1, Gender.Male, "From the Latin name Cassius"),
            new HumanName("Cedric", 1, Gender.Male, "From the name Cerdic"),
            new HumanName("Chad", 1, Gender.Male, "From old English boys name Ceadda who was a saint"),
            new HumanName("Chase", 1, Gender.Male, "Originates from a huntsman"),
            new HumanName("Clay", 1, Gender.Male, "Pet name of Clayton"),
            new HumanName("Clayton", 1, Gender.Male, "From people who lived in the clay settlement"),
            new HumanName("Clement", 1, Gender.Male, "From the Latin name Clemens"),
            new HumanName("Clifford", 1, Gender.Male, "Orginates form the words Cliff and ford"),
            new HumanName("Cole", 1, Gender.Male, "Old English male name Cola – meaning black"),
            new HumanName("Coleman", 1, Gender.Male, "From a man who burns cole"),
            new HumanName("Conrad", 1, Gender.Male, "Means bold in counsel"),
            new HumanName("Constant", 1, Gender.Male, "Means steadfast"),
            new HumanName("Conway", 1, Gender.Male, "Celtic name and it means holy river"),
            new HumanName("Corwin", 1, Gender.Male, "This name means from beyond a hill"),
            new HumanName("Crispin", 1, Gender.Male, "Means curly headed"),
            new HumanName("Crosby", 1, Gender.Male, "This English boy’s names means dweller by town cross"),
            new HumanName("Curtis", 1, Gender.Male, "This name means courteous"),
            new HumanName("Dale", 1, Gender.Male, "Someone who lived in a valley"),
            new HumanName("Daley", 1, Gender.Male, "This name means gathering (from the Gaelic word dalaigh)"),
            new HumanName("Damon", 1, Gender.Male, "Means to tame"),
            new HumanName("Dane", 1, Gender.Male, "Means Dean originated South East England"),
            new HumanName("Dene", 1, Gender.Male, "An alternative spelling for Dean"),
            new HumanName("Denton", 1, Gender.Male, "Meaning valley settlement"),
            new HumanName("Desmond", 1, Gender.Male, "A local name from someone from Munster"),
            new HumanName("Digby", 1, Gender.Male, "Name originating from Lincolnshire meaning ditch settlement"),
            new HumanName("Don", 1, Gender.Male, "Pet form of Dominic"),
            new HumanName("Doran", 1, Gender.Male, "Meaning excile wanderer"),
            new HumanName("Dorian", 1, Gender.Male, "Created by Oscar Wild"),
            new HumanName("Doyle", 1, Gender.Male, "English varient of Dougal"),
            new HumanName("Drake", 1, Gender.Male, "Old English name that means Dragon"),
            new HumanName("Drogo", 1, Gender.Male, "Possibly means ghostly/phantom"),
            new HumanName("Dudley", 1, Gender.Male, "From the place name in Birmingham"),
            new HumanName("Duggie", 1, Gender.Male, "English name short for Dougless"),
            new HumanName("Duncan", 1, Gender.Male, "From the Gaelic name Donnchadh"),
            new HumanName("Dunstan", 1, Gender.Male, "Old English name meaning dark stone"),
            new HumanName("Dwight", 1, Gender.Male, "Comes from the name Diot and related to Dennis"),
            new HumanName("Earl", 1, Gender.Male, "From a Nobleman"),
            new HumanName("Ebenezer", 1, Gender.Male, "Means rock or stone of help"),
            new HumanName("Eden", 1, Gender.Male, "From the name Edun"),
            new HumanName("Edgar", 1, Gender.Male, "Names composed of the words that mean fortunate/rich and spear"),
            new HumanName("Edwin", 1, Gender.Male, "Mean prosperus friend"),
            new HumanName("Egbert", 1, Gender.Male, "Means bright of edge of a sword"),
            new HumanName("Elbert", 1, Gender.Male, "English name a varient of the name Albert meaning nobly and bright"),
            new HumanName("Eldon", 1, Gender.Male, "After the place name in Durham"),
            new HumanName("Ellery", 1, Gender.Male, "Old English name meaning alder tree"),
            new HumanName("Elmer", 1, Gender.Male, "Old English name meaning Old and Noble"),
            new HumanName("Elmer", 1, Gender.Male, "Means noble and famous"),
            new HumanName("Elton", 1, Gender.Male, "Local name from places in England"),
            new HumanName("Elton", 1, Gender.Male, "Local name from places in England"),
            new HumanName("Elvis", 1, Gender.Male, "Made famous by Elvis Presley"),
            new HumanName("Emerson", 1, Gender.Male, "Old English boy’s name that means the son of Emery"),
            new HumanName("Emmett", 1, Gender.Male, "From the female name Emmet"),
            new HumanName("Erasmus", 1, Gender.Male, "Means to love"),
            new HumanName("Ernest", 1, Gender.Male, "From eorost (battle to death)"),
            new HumanName("Errol", 1, Gender.Male, "From a placename"),
            new HumanName("Esmond", 1, Gender.Male, "From the words protective and grace"),
            new HumanName("Eugene", 1, Gender.Male, "From Eugenios"),
            new HumanName("Everett", 1, Gender.Male, "Variant of the name Everard"),
            new HumanName("Ike", 1, Gender.Male, "A form of Isaac."),
            new HumanName("Ingram", 1, Gender.Male, "Ingram from medieval name Engelram."),
            new HumanName("Irving", 1, Gender.Male, "Local place name in near Dumfries."),
            new HumanName("Isaiah", 1, Gender.Male, "Biblical name meaning god is salvation."),
            new HumanName("Ivor", 1, Gender.Male, "This male name means bowed warrior."),
            new HumanName("Jed", 1, Gender.Male, "Short for Jedidiah."),
            new HumanName("Jefferson", 1, Gender.Male, "Son of Jeffrey."),
            new HumanName("Jerrold", 1, Gender.Male, "Jerrold from Gerald."),
            new HumanName("Jesse", 1, Gender.Male, "Meaning gift."),
            new HumanName("Jethro", 1, Gender.Male, "Derived from Hebrew name Ithra."),
            new HumanName("Jody", 1, Gender.Male, "Jody can be a male name but it’s more commonly female name."),
            new HumanName("Johnathan", 1, Gender.Male, "Variant of Jonathan."),
            new HumanName("Judd", 1, Gender.Male, "Judd pet form of Jordan."),
            new HumanName("Kelsey", 1, Gender.Male, "Means ship’ s victory."),
            new HumanName("Kemp", 1, Gender.Male, "Means athlete or wrestler."),
            new HumanName("Kenton", 1, Gender.Male, "Kenton local places in England."),
            new HumanName("Kermit", 1, Gender.Male, "Means son of Dermot."),
            new HumanName("Kerr", 1, Gender.Male, "Someone who dwells by brushwood"),
            new HumanName("King", 1, Gender.Male, "From the name of the monarch."),
            new HumanName("Kingsley", 1, Gender.Male, "From places in Hampshire and Staffordshire.  Means old wood."),
            new HumanName("Kyran", 1, Gender.Male, "English spelling of Kieran."),
            new HumanName("Leland", 1, Gender.Male, "Someone from  a fallow land."),
            new HumanName("Lester", 1, Gender.Male, "name is from the English city Leicester."),
            new HumanName("Lewie", 1, Gender.Male, "name is from the English city Leicester."),
            new HumanName("Lincoln", 1, Gender.Male, "From the English city Lincoln."),
            new HumanName("Linden", 1, Gender.Male, "Means thr lime tree."),
            new HumanName("Linford", 1, Gender.Male, "A mix of the words lime tree and ford."),
            new HumanName("Linsay", 1, Gender.Male, "Linsay wetlands belonging to Lincon."),
            new HumanName("Linton", 1, Gender.Male, "Place names in England."),
            new HumanName("Lorne", 1, Gender.Male, "Origin unknown."),
            new HumanName("Luther", 1, Gender.Male, "Means people army."),
            new HumanName("Magnus", 1, Gender.Male, "Mean’s great"),
            new HumanName("Mallory", 1, Gender.Male, "Means unhappy or unlucky"),
            new HumanName("Manfred", 1, Gender.Male, "Means peace man"),
            new HumanName("Manley", 1, Gender.Male, "Places in England (Devon and Cheshire)"),
            new HumanName("Marc", 1, Gender.Male, "From the name Marcus (see Mark)"),
            new HumanName("Marian", 1, Gender.Male, "From the name Marion"),
            new HumanName("Marmaduke", 1, Gender.Male, "Origin unknown."),
            new HumanName("Marsh", 1, Gender.Male, "Someone who lives by a march"),
            new HumanName("Marshall", 1, Gender.Male, "Means horse worker"),
            new HumanName("Marty", 1, Gender.Male, "Pet form of Martin"),
            new HumanName("Maurice", 1, Gender.Male, "English boys name from the Latin name Mauricius"),
            new HumanName("Maynard", 1, Gender.Male, "Means strong and brave"),
            new HumanName("Melvin", 1, Gender.Male, "A lake in Ireland"),
            new HumanName("Milo", 1, Gender.Male, "Form of Miles"),
            new HumanName("Monroe", 1, Gender.Male, "Anglisised version of Munro"),
            new HumanName("Montague", 1, Gender.Male, "Placename Name"),
            new HumanName("Mortimer", 1, Gender.Male, "Means dead sea"),
            new HumanName("Morton", 1, Gender.Male, "Place by the the moor"),
            new HumanName("Nathaniel", 1, Gender.Male, "Means the gift of God"),
            new HumanName("Neal", 1, Gender.Male, "Form of Neil"),
            new HumanName("Nelson", 1, Gender.Male, "Derived from Neil or Nell"),
            new HumanName("Obadiah", 1, Gender.Male, "Servant of God"),
            new HumanName("Omar", 1, Gender.Male, "Biblical name"),
            new HumanName("Orson", 1, Gender.Male, "Means like the Bear cub"),
            new HumanName("Orville", 1, Gender.Male, "Created by Fanny Burney"),
            new HumanName("Osbert", 1, Gender.Male, "Famous/Bright God"),
            new HumanName("Otis", 1, Gender.Male, "Son of Ote"),
            new HumanName("Pancras", 1, Gender.Male, "From Greek name Pankratios"),
            new HumanName("Perce", 1, Gender.Male, "Pet form of Percy"),
            new HumanName("Percival", 1, Gender.Male, "From the French name Perceval"),
            new HumanName("Philbert", 1, Gender.Male, "Means most bright"),
            new HumanName("Philo", 1, Gender.Male, "From the name Philon"),
            new HumanName("Piers", 1, Gender.Male, "Middle English male name derived from of Peter"),
            new HumanName("Quentin", 1, Gender.Male, "From the Latin name Quintinus"),
            new HumanName("Quincy", 1, Gender.Male, "Made famous by John Quincy Adams (2nd USA president)"),
            new HumanName("Quintus", 1, Gender.Male, "Meaning 5th"),
            new HumanName("Rafe", 1, Gender.Male, "Short for Ralph"),
            new HumanName("Randall", 1, Gender.Male, "From Randolf"),
            new HumanName("Randolph", 1, Gender.Male, "Means shield like a wolf"),
            new HumanName("Randy", 1, Gender.Male, "Pet forms of Randall or Randolf"),
            new HumanName("Raphael", 1, Gender.Male, "Means god heals"),
            new HumanName("Reg", 1, Gender.Male, "Pet name for Reginald"),
            new HumanName("Reggie", 1, Gender.Male, "Pet form of Reg"),
            new HumanName("Reginald", 1, Gender.Male, "From the name Reginaldus"),
            new HumanName("Remus", 1, Gender.Male, "Brother of the Roma Romulas"),
            new HumanName("Renfred", 1, Gender.Male, "Peacemaker"),
            new HumanName("Rex", 1, Gender.Male, "This name means king"),
            new HumanName("Reynard", 1, Gender.Male, "Means brave decision"),
            new HumanName("Rod", 1, Gender.Male, "English pet form of the name Rodney and Roderick"),
            new HumanName("Rodney", 1, Gender.Male, "Originates from a place name. Made popular by Admiral Lord Rodney."),
            new HumanName("Rolf", 1, Gender.Male, "Famous wolf"),
            new HumanName("Rowan", 1, Gender.Male, "Means little red one"),
            new HumanName("Rowley", 1, Gender.Male, "From the name Roly"),
            new HumanName("Royle", 1, Gender.Male, "Means rye hill"),
            new HumanName("Rufus", 1, Gender.Male, "Nickname of someone with red hair"),
            new HumanName("Rusty", 1, Gender.Male, "Someone with red hair"),
            new HumanName("Sandford", 1, Gender.Male, "Version of Sanford"),
            new HumanName("Sanford", 1, Gender.Male, "English place name"),
            new HumanName("Seymour", 1, Gender.Male, "From placename in Normandy Saint Maur"),
            new HumanName("Shawn", 1, Gender.Male, "from Sean"),
            new HumanName("Sheldon", 1, Gender.Male, "From place names in England"),
            new HumanName("Sigmund", 1, Gender.Male, "Means victorious protector"),
            new HumanName("Skipper", 1, Gender.Male, "From the captain of a ship"),
            new HumanName("Spencer", 1, Gender.Male, "Made famous by the actor Spencer Tracy"),
            new HumanName("Spike", 1, Gender.Male, "Some male with Spiky hair"),
            new HumanName("Stephan", 1, Gender.Male, "Variant of Stephen"),
            new HumanName("Sterling", 1, Gender.Male, "High Quality"),
            new HumanName("Tad", 1, Gender.Male, "Short for Tadhg"),
            new HumanName("Teddy", 1, Gender.Male, "Pet form of Ted"),
            new HumanName("Theobold", 1, Gender.Male, "Means brave people"),
            new HumanName("Theodore", 1, Gender.Male, "Means god’s gift"),
            new HumanName("Tristram", 1, Gender.Male, "From Celtic legend"),
            new HumanName("Troy", 1, Gender.Male, "Named after the city Troy"),
            new HumanName("Truman", 1, Gender.Male, "Means a trustful/loyal man"),
            new HumanName("Ulric", 1, Gender.Male, "Means wolf powert"),
            new HumanName("Urban", 1, Gender.Male, "Means city dweller"),
            new HumanName("Valentine", 1, Gender.Male, "Means healthy and strong"),
            new HumanName("Vere", 1, Gender.Male, "Place names in France"),
            new HumanName("Vergil", 1, Gender.Male, "From the name Virgil"),
            new HumanName("Vernon", 1, Gender.Male, "Place names in France"),
            new HumanName("Vincent", 1, Gender.Male, "Means conquering"),
            new HumanName("Virgil", 1, Gender.Male, "from Latin Vergilius"),
            new HumanName("Waally", 1, Gender.Male, "Pert form of Walter"),
            new HumanName("Wade", 1, Gender.Male, "A person who lives by a ford"),
            new HumanName("Wallace", 1, Gender.Male, "Means foreigner"),
            new HumanName("Ward", 1, Gender.Male, "Guard"),
            new HumanName("Warren", 1, Gender.Male, "Popular name originating form Normandy"),
            new HumanName("Warwick", 1, Gender.Male, "From the place near Birmingham in England"),
            new HumanName("Watkin", 1, Gender.Male, "Also common as a surname"),
            new HumanName("Wesley", 1, Gender.Male, "Popular from John Wesley the founder of the methodist church"),
            new HumanName("Wilberforce", 1, Gender.Male, "Name originating from North Yorkshire"),
            new HumanName("Wilbur", 1, Gender.Male, "Desire and fortress"),
            new HumanName("Wilfrid", 1, Gender.Male, "Means desire peace"),
            new HumanName("Wilmot", 1, Gender.Male, "Pet form of Will"),
            new HumanName("Windsor", 1, Gender.Male, "From the place name in England"),
            new HumanName("Winston", 1, Gender.Male, "Means joy and stone"),
            new HumanName("Winton", 1, Gender.Male, "Mean enclosed pasture"),
            new HumanName("Woody", 1, Gender.Male, "Short form of Woodrow"),
            new HumanName("Zeph", 1, Gender.Male, "Short for Zephaniah"),

            // Female Names: 450
            new HumanName("Amelia", 5, Gender.Female, "A mix  between the names Emilia and Amalia"),
            new HumanName("Ann", 5, Gender.Female, "English spelling of Anne"),
            new HumanName("Ava", 5, Gender.Female, "Was a 9th century saint St Ava or Avis"),
            new HumanName("Charlotte", 5, Gender.Female, "From the name Charles"),
            new HumanName("Chloe", 5, Gender.Female, "This name originate from the Greek name khlóē"),
            new HumanName("Daisy", 5, Gender.Female, "The name comes from the flower"),
            new HumanName("Ella", 5, Gender.Female, "A variant of the name Ellen"),
            new HumanName("Ellie", 5, Gender.Female, "Pet form of Eleanor/Ellen/Helen"),
            new HumanName("Emily", 5, Gender.Female, "Feminine version of the name Aemilius"),
            new HumanName("Emma", 5, Gender.Female, "From the names Ermintrude and Irmgard"),
            new HumanName("Evie", 5, Gender.Female, "Pet form of Eve or Eva"),
            new HumanName("Grace", 5, Gender.Female, "From the name Gratia"),
            new HumanName("Helen", 5, Gender.Female, "English version of the Greek name Helene"),
            new HumanName("Imogen", 5, Gender.Female, "From Shakespeare"),
            new HumanName("Isabella", 5, Gender.Female, "From Isabel"),
            new HumanName("Isabelle", 5, Gender.Female, "From the name Isabel"),
            new HumanName("Jessica", 5, Gender.Female, "From Shakespeare"),
            new HumanName("Katherine", 5, Gender.Female, "From the saint"),
            new HumanName("Laura", 5, Gender.Female, "From the name Laurus"),
            new HumanName("Lilly", 5, Gender.Female, "From the flower"),
            new HumanName("Lily", 5, Gender.Female, "From the flower"),
            new HumanName("Lucy", 5, Gender.Female, "From the old French name Lucie"),
            new HumanName("Mary", 5, Gender.Female, "English girl’s name from Marie or Maria"),
            new HumanName("Olivia", 5, Gender.Female, "From Shakespeare"),
            new HumanName("Phoebe", 5, Gender.Female, "From the moon goddess"),
            new HumanName("Poppy", 5, Gender.Female, "From the name of the flower"),
            new HumanName("Rachel", 5, Gender.Female, "A biblical name"),
            new HumanName("Ruby", 5, Gender.Female, "From the red gemstone"),
            new HumanName("Scarlett", 5, Gender.Female, "Name based on the colour red"),
            new HumanName("Abigail", 4, Gender.Female, "Biblical name meaning ‘father of exaltation’"),
            new HumanName("Adele", 4, Gender.Female, "English form of the French name Adéle"),
            new HumanName("Alice", 4, Gender.Female, "Based on the girl’s name Adelaide"),
            new HumanName("Amanda", 4, Gender.Female, "Means loveable"),
            new HumanName("Amber", 4, Gender.Female, "From the gemstone amber"),
            new HumanName("Amy", 4, Gender.Female, "Anglicized from Amee (old French)"),
            new HumanName("Angela", 4, Gender.Female, "This name means Angelic"),
            new HumanName("Anne", 4, Gender.Female, "From the hebrew girl’s name Hanna"),
            new HumanName("Beth", 4, Gender.Female, "From Elizabeth"),
            new HumanName("Brooke", 4, Gender.Female, "From the Brook"),
            new HumanName("Eleanor", 4, Gender.Female, "A derived from Helen"),
            new HumanName("Elizabeth", 4, Gender.Female, "Made popular by Queen Elizabeth I"),
            new HumanName("Florence", 4, Gender.Female, "From the name Florentius"),
            new HumanName("Gracie", 4, Gender.Female, "Pet form of the English name Grace"),
            new HumanName("Hollie", 4, Gender.Female, "Alternative spelling of the name Holly"),
            new HumanName("Isabel", 4, Gender.Female, "From the Spanish version of Elizabeth"),
            new HumanName("Jane", 4, Gender.Female, "Female name for John"),
            new HumanName("Jasmine", 4, Gender.Female, "From a flower"),
            new HumanName("Katie", 4, Gender.Female, "From the name Kate (and therefore Katherine)"),
            new HumanName("Lacey", 4, Gender.Female, "From the surname"),
            new HumanName("Lexi", 4, Gender.Female, "From Alexandra"),
            new HumanName("Lisa", 4, Gender.Female, "From the French name Lise"),
            new HumanName("Lola", 4, Gender.Female, "From Dolores"),
            new HumanName("Maggie", 4, Gender.Female, "Pet form of Margaret"),
            new HumanName("Maya", 4, Gender.Female, "Influenced by May"),
            new HumanName("Millie", 4, Gender.Female, "Pet form of Amelia, Camilla, Melissa"),
            new HumanName("Molly", 4, Gender.Female, "Version of the girl’s name Mary"),
            new HumanName("Rosie", 4, Gender.Female, "Pet form of Rosemary"),
            new HumanName("Sabrina", 4, Gender.Female, "From the Celtic legend give name to Severn River"),
            new HumanName("Samantha", 4, Gender.Female, "Origin unknown"),
            new HumanName("Sharon", 4, Gender.Female, "From the place in the bible"),
            new HumanName("Summer", 4, Gender.Female, "From the season"),
            new HumanName("Susan", 4, Gender.Female, "From the name Susanna"),
            new HumanName("Vanessa", 4, Gender.Female, "Created by Jonathan Swift"),
            new HumanName("Viola", 4, Gender.Female, "Means violet"),
            new HumanName("Alex", 3, Gender.Female, "Variant of the name Alexandra or Alexis"),
            new HumanName("Alexandra", 3, Gender.Female, "From the words ‘Defender of Mankind’ and Warrior"),
            new HumanName("Alison", 3, Gender.Female, "Norman diminutive of Alice"),
            new HumanName("Annabelle", 3, Gender.Female, "Likely from Amabel"),
            new HumanName("April", 3, Gender.Female, "English form of aprilis. Also a month."),
            new HumanName("Barbara", 3, Gender.Female, "Means foreign woman"),
            new HumanName("Bea", 3, Gender.Female, "Short form of Beatrix or Beatrice"),
            new HumanName("Beatrix", 3, Gender.Female, "Voyager/Blessed"),
            new HumanName("Becky", 3, Gender.Female, "From the girl’s name Rebecca"),
            new HumanName("Bella", 3, Gender.Female, "Short form of Isabella"),
            new HumanName("Bethany", 3, Gender.Female, "Village outside Jerusalem"),
            new HumanName("Betty", 3, Gender.Female, "From the English girl’s name Elizabeth"),
            new HumanName("Catherine", 3, Gender.Female, "A variant of the name Katherine"),
            new HumanName("Cheryl", 3, Gender.Female, "Origins unknown, possibly from Cherry and Beryl"),
            new HumanName("Christine", 3, Gender.Female, "Form of the girl’s name Christina"),
            new HumanName("Deborah", 3, Gender.Female, "Biblical name"),
            new HumanName("Eliza", 3, Gender.Female, "Short form of Elizabeth"),
            new HumanName("Ellen", 3, Gender.Female, "Form of Helen"),
            new HumanName("Emmy", 3, Gender.Female, "Pet form of Emma or Emily"),
            new HumanName("Evelyn", 3, Gender.Female, "Comes from the girl’s name Aveline"),
            new HumanName("Faith", 3, Gender.Female, "Faith and belief in God"),
            new HumanName("Gail", 3, Gender.Female, "From Abigail"),
            new HumanName("Georgia", 3, Gender.Female, "Feminine of George"),
            new HumanName("Georgiana", 3, Gender.Female, "Feminine of George"),
            new HumanName("Harriet", 3, Gender.Female, "English version of the name Henriette"),
            new HumanName("Holly", 3, Gender.Female, "The name comes from the holly bush"),
            new HumanName("Jacqueline", 3, Gender.Female, "Feminine of Jacques"),
            new HumanName("Jennet", 3, Gender.Female, "English spelling of Jeannette"),
            new HumanName("Jennifer", 3, Gender.Female, "From the name Guinevere"),
            new HumanName("Jenny", 3, Gender.Female, "From the English girl’s name Jennifer"),
            new HumanName("Jess", 3, Gender.Female, "Pet form of Jessica"),
            new HumanName("Jewel", 3, Gender.Female, "From the gemstone"),
            new HumanName("Kay", 3, Gender.Female, "Short form of Katherine"),
            new HumanName("Kayla", 3, Gender.Female, "Variants of Kay"),
            new HumanName("Kelly", 3, Gender.Female, "Origin unknown"),
            new HumanName("Kim", 3, Gender.Female, "From the girl’s name Kimberley"),
            new HumanName("Kimberley", 3, Gender.Female, "From the place in South Africa"),
            new HumanName("Kyle", 3, Gender.Female, "Means narrow channel"),
            new HumanName("Kylie", 3, Gender.Female, "Mean boomerang"),
            new HumanName("Lauren", 3, Gender.Female, "From the name Laurence"),
            new HumanName("Leanne", 3, Gender.Female, "From the names Lee & Anne"),
            new HumanName("Leona", 3, Gender.Female, "From the name Leon"),
            new HumanName("Lexy", 3, Gender.Female, "From Alexandra (see Lexi for more information)"),
            new HumanName("Linda", 3, Gender.Female, "From the name Belinda"),
            new HumanName("Linda", 3, Gender.Female, "Origin unknown"),
            new HumanName("Lindsay", 3, Gender.Female, "The name originates from the place Lincoln"),
            new HumanName("Liz", 3, Gender.Female, "From the name Elizabeth"),
            new HumanName("Mandy", 3, Gender.Female, "From Amanda"),
            new HumanName("Margaret", 3, Gender.Female, "From the French name Marguerite"),
            new HumanName("Maxine", 3, Gender.Female, "Feminine version of the name Max"),
            new HumanName("Meg", 3, Gender.Female, "Pet form of Margaret"),
            new HumanName("Melanie", 3, Gender.Female, "From Melania (dark haired)"),
            new HumanName("Melinda", 3, Gender.Female, "A name derived from Melanie and Lucinda"),
            new HumanName("Melissa", 3, Gender.Female, "This name means bee"),
            new HumanName("Miranda", 3, Gender.Female, "From Shakespeare"),
            new HumanName("Nancy", 3, Gender.Female, "Origin unknown"),
            new HumanName("Nell", 3, Gender.Female, "Pet form of Eleanor/Ellen/Helen"),
            new HumanName("Pamela", 3, Gender.Female, "Created by a poet Philip Sidney"),
            new HumanName("Paula", 3, Gender.Female, "Form of Paul"),
            new HumanName("Philippa", 3, Gender.Female, "From the name Philip"),
            new HumanName("Polly", 3, Gender.Female, "Variant of Molly"),
            new HumanName("Robin", 3, Gender.Female, "Feminine of Robert"),
            new HumanName("Rose", 3, Gender.Female, "From the flower"),
            new HumanName("Rosemary", 3, Gender.Female, "From the herb"),
            new HumanName("Sally", 3, Gender.Female, "From the name Sarah"),
            new HumanName("Sandra", 3, Gender.Female, "From the name Alessandra"),
            new HumanName("Shannon", 3, Gender.Female, "From the river in Ireland"),
            new HumanName("Sheila", 3, Gender.Female, "From the Gaelic name Sile"),
            new HumanName("Skye", 3, Gender.Female, "From the English name Sky"),
            new HumanName("Sue", 3, Gender.Female, "Pet form of Susan"),
            new HumanName("Tara", 3, Gender.Female, "This English name means hill"),
            new HumanName("Tasha", 3, Gender.Female, "Short for Natasha"),
            new HumanName("Tessa", 3, Gender.Female, "From Theresa"),
            new HumanName("Tiffany", 3, Gender.Female, "Means epiphany"),
            new HumanName("Tracy", 3, Gender.Female, "From the French place"),
            new HumanName("Valerie", 3, Gender.Female, "Means healthy and strong"),
            new HumanName("Vicky", 3, Gender.Female, "Pet form of Victoria"),
            new HumanName("Victoria", 3, Gender.Female, "Means victorious"),
            new HumanName("Wendy", 3, Gender.Female, "Invented in the play Peter Pan"),
            new HumanName("Whitney", 3, Gender.Female, "After places in England"),
            new HumanName("Willow", 3, Gender.Female, "From the tree"),
            new HumanName("Zoe", 3, Gender.Female, "Means Life"),
            new HumanName("Abbey", 2, Gender.Female, "Variant of Abigail"),
            new HumanName("Abbie", 2, Gender.Female, "Variant of Abigail"),
            new HumanName("Adrienne", 2, Gender.Female, "Feminine of the name Adrian"),
            new HumanName("Agatha", 2, Gender.Female, "Good or honourable from agathos"),
            new HumanName("Aileen", 2, Gender.Female, "Variant of the girl’s name Eileen"),
            new HumanName("Alma", 2, Gender.Female, "River in the Crimea"),
            new HumanName("Andrea", 2, Gender.Female, "Feminine form of the name Andrew"),
            new HumanName("Anthea", 2, Gender.Female, "From the Greek name Antheia"),
            new HumanName("Ashley", 2, Gender.Female, "Derived from old English Ash and Wood"),
            new HumanName("Audrey", 2, Gender.Female, "From an old English name which means noble strength"),
            new HumanName("Avril", 2, Gender.Female, "Taken from April"),
            new HumanName("Babs", 2, Gender.Female, "Pet form of the girl’s name Barbara"),
            new HumanName("Belinda", 2, Gender.Female, "Uncertain origin"),
            new HumanName("Berry", 2, Gender.Female, "From the fruit"),
            new HumanName("Betsy", 2, Gender.Female, "Pet form of Elizabeth"),
            new HumanName("Beverly", 2, Gender.Female, "From a Beaver Stream/Meadow"),
            new HumanName("Bobbie", 2, Gender.Female, "Variant of the name Roberta"),
            new HumanName("Bridget", 2, Gender.Female, "Anglicized from Brighid"),
            new HumanName("Britney", 2, Gender.Female, "From Britain"),
            new HumanName("Camilla", 2, Gender.Female, "From the old Roman name Camillus"),
            new HumanName("Carly", 2, Gender.Female, "Pet form of Carla"),
            new HumanName("Carol", 2, Gender.Female, "Anglisized form of Carolus"),
            new HumanName("Caroline", 2, Gender.Female, "Anglisized form of Carolus"),
            new HumanName("Carrie", 2, Gender.Female, "Form of Caroline"),
            new HumanName("Cathy", 2, Gender.Female, "A short form of Catherine"),
            new HumanName("Charity", 2, Gender.Female, "Affection/’Love for fellow man’"),
            new HumanName("Charlene", 2, Gender.Female, "Originates from the name Charles"),
            new HumanName("Charlie", 2, Gender.Female, "Pet name for Charles"),
            new HumanName("Chelsea", 2, Gender.Female, "Means Harbour, and place in London"),
            new HumanName("Christina", 2, Gender.Female, "Feminine form of Christian"),
            new HumanName("Clara", 2, Gender.Female, "Feminine form of Clarus"),
            new HumanName("Clare", 2, Gender.Female, "A form of Clara"),
            new HumanName("Clarissa", 2, Gender.Female, "A version of the name Clarice"),
            new HumanName("Claudia", 2, Gender.Female, "Originates from the name Claudius"),
            new HumanName("Connie", 2, Gender.Female, "Pet form of Constance"),
            new HumanName("Cynthia", 2, Gender.Female, "From the girl’s name Kynthia"),
            new HumanName("Dawn", 2, Gender.Female, "Mean in English – day break"),
            new HumanName("Delia", 2, Gender.Female, "From the place Delos"),
            new HumanName("Diana", 2, Gender.Female, "Roman goddess of the moon and hunting"),
            new HumanName("Donna", 2, Gender.Female, "From the name Madonna"),
            new HumanName("Doreen", 2, Gender.Female, "From the name Dora"),
            new HumanName("Dorothy", 2, Gender.Female, "From the English girl’s name Dorothea"),
            new HumanName("Edith", 2, Gender.Female, "From the words for fortune, riches and strife"),
            new HumanName("Elaine", 2, Gender.Female, "A derived from Helen"),
            new HumanName("Elena", 2, Gender.Female, "Form of Helen"),
            new HumanName("Erin", 2, Gender.Female, "Angliszed name from Eirinn"),
            new HumanName("Ethel", 2, Gender.Female, "Means noble"),
            new HumanName("Eve", 2, Gender.Female, "A biblical name"),
            new HumanName("Evonne", 2, Gender.Female, "English Girl’s name based on Yvonne"),
            new HumanName("Fay", 2, Gender.Female, "Half sister of king Arthur"),
            new HumanName("Felicity", 2, Gender.Female, "Means good luck"),
            new HumanName("Fern", 2, Gender.Female, "Means fern plant"),
            new HumanName("Gale", 2, Gender.Female, "From Abigail"),
            new HumanName("Gaynor", 2, Gender.Female, "From Guinevere"),
            new HumanName("Gillian", 2, Gender.Female, "Feminine of Julian"),
            new HumanName("Gloria", 2, Gender.Female, "From glorious"),
            new HumanName("Hayley", 2, Gender.Female, "Place in Oxfordshire"),
            new HumanName("Hazel", 2, Gender.Female, "From the nuts"),
            new HumanName("Heather", 2, Gender.Female, "From the heather plant"),
            new HumanName("Hilary", 2, Gender.Female, "From the name Hilarius"),
            new HumanName("Honey", 2, Gender.Female, "From honey that bees produce"),
            new HumanName("Hope", 2, Gender.Female, "From the word meaning hope"),
            new HumanName("Irene", 2, Gender.Female, "The name means peace"),
            new HumanName("Iris", 2, Gender.Female, "This English name means rainbow"),
            new HumanName("Jackie", 2, Gender.Female, "From Jacqueline"),
            new HumanName("Jade", 2, Gender.Female, "From a gemstone"),
            new HumanName("Janet", 2, Gender.Female, "From the name Jane"),
            new HumanName("Janette", 2, Gender.Female, "From the name Jane"),
            new HumanName("Janice", 2, Gender.Female, "Mix between Jan and Frances"),
            new HumanName("Jean", 2, Gender.Female, "From the name Jeanne"),
            new HumanName("Jessie", 2, Gender.Female, "Pet form of Jean"),
            new HumanName("Jill", 2, Gender.Female, "From Gillian"),
            new HumanName("Joan", 2, Gender.Female, "From the name Joanna"),
            new HumanName("Jodie", 2, Gender.Female, "Uncertain origin"),
            new HumanName("Josephine", 2, Gender.Female, "The analgised version of the French name"),
            new HumanName("Joy", 2, Gender.Female, "Meaning delight"),
            new HumanName("Joyce", 2, Gender.Female, "From the name Josce"),
            new HumanName("Juliet", 2, Gender.Female, "English version of the name Juliette"),
            new HumanName("June", 2, Gender.Female, "From the month of the year"),
            new HumanName("Justine", 2, Gender.Female, "Female version of the name Justin"),
            new HumanName("Kate", 2, Gender.Female, "From the name Katherine"),
            new HumanName("Katy", 2, Gender.Female, "From Katie"),
            new HumanName("Kayley", 2, Gender.Female, "Means slender"),
            new HumanName("Kerry", 2, Gender.Female, "From the Irish county"),
            new HumanName("Lee", 2, Gender.Female, "Clearing"),
            new HumanName("Lena", 2, Gender.Female, "From names ending in lena or lina like Helena"),
            new HumanName("Lesley", 2, Gender.Female, "From Leslie"),
            new HumanName("Libby", 2, Gender.Female, "From the English name Elizabeth"),
            new HumanName("Lilian", 2, Gender.Female, "Origin unknown"),
            new HumanName("Lindy", 2, Gender.Female, "From the name Linda"),
            new HumanName("Linette", 2, Gender.Female, "A variant of the name Linnette"),
            new HumanName("Lorraine", 2, Gender.Female, "A place name Lorraine in France"),
            new HumanName("Louise", 2, Gender.Female, "Female version of Louis"),
            new HumanName("Lynette", 2, Gender.Female, "From the name Lynn"),
            new HumanName("Mabel", 2, Gender.Female, "The name means lovely"),
            new HumanName("Madeline", 2, Gender.Female, "A biblical name"),
            new HumanName("Madonna", 2, Gender.Female, "From biblical name My Lady"),
            new HumanName("Maggie", 2, Gender.Female, "From the name Margaret"),
            new HumanName("Marilyn", 2, Gender.Female, "Originates from the name Mary"),
            new HumanName("Maureen", 2, Gender.Female, "From the Irish name Mairin"),
            new HumanName("Melody", 2, Gender.Female, "From the melody of a song"),
            new HumanName("Monica", 2, Gender.Female, "Origin unknown"),
            new HumanName("Muriel", 2, Gender.Female, "From the Celtic name Muireall"),
            new HumanName("Nadia", 2, Gender.Female, "English version of the name Nadezhda"),
            new HumanName("Nessa", 2, Gender.Female, "From Agnessa"),
            new HumanName("Nicola", 2, Gender.Female, "From the name Nicholas"),
            new HumanName("Norma", 2, Gender.Female, "Origin unknown"),
            new HumanName("Olive", 2, Gender.Female, "From the olive plant"),
            new HumanName("Patricia", 2, Gender.Female, "Feminine version of Patrick"),
            new HumanName("Patsy", 2, Gender.Female, "Pet form of Patricia"),
            new HumanName("Peggy", 2, Gender.Female, "From Maggie"),
            new HumanName("Penelope", 2, Gender.Female, "From mythology"),
            new HumanName("Phyllis", 2, Gender.Female, "From mythology"),
            new HumanName("Pippa", 2, Gender.Female, "From the English girl’s name Philippa"),
            new HumanName("Rita", 2, Gender.Female, "From the name Margarita"),
            new HumanName("Ronnie", 2, Gender.Female, "From Veronica"),
            new HumanName("Roxanne", 2, Gender.Female, "From the name Roxana"),
            new HumanName("Sadie", 2, Gender.Female, "From the name Sarah"),
            new HumanName("Sandy", 2, Gender.Female, "From the name Alexandra"),
            new HumanName("Selena", 2, Gender.Female, "Origin unknown"),
            new HumanName("Shirley", 2, Gender.Female, "From place in England"),
            new HumanName("Sybil", 2, Gender.Female, "From the Sibylla"),
            new HumanName("Sybil", 2, Gender.Female, "From the Greek name Sibylla"),
            new HumanName("Sylvia", 2, Gender.Female, "From Silvia"),
            new HumanName("Tammy", 2, Gender.Female, "Pet form of Tamara"),
            new HumanName("Tamsin", 2, Gender.Female, "Linked to the name Thomas"),
            new HumanName("Tawny", 2, Gender.Female, "From the colour of the owl"),
            new HumanName("Trisha", 2, Gender.Female, "From Patricia"),
            new HumanName("Trixie", 2, Gender.Female, "Form of Beatrix"),
            new HumanName("Violet", 2, Gender.Female, "From the flower"),
            new HumanName("Virginia", 2, Gender.Female, "From the name Virgil"),
            new HumanName("Winifred", 2, Gender.Female, "Joy and Peace"),
            new HumanName("Ada", 1, Gender.Female, "Pet forms of the girl’s names Adele or Adelaide"),
            new HumanName("Adelaide", 1, Gender.Female, "English form of the French name Adélaïde"),
            new HumanName("Agnes", 1, Gender.Female, "Pure, or holy from the word hagnos"),
            new HumanName("Alana", 1, Gender.Female, "Feminine form of Alan"),
            new HumanName("Alina", 1, Gender.Female, "From the names Alina and Linda"),
            new HumanName("Arlene", 1, Gender.Female, "Probably based on Marlene or Charlene"),
            new HumanName("Bernice", 1, Gender.Female, "From Berenice"),
            new HumanName("Bertha", 1, Gender.Female, "Bright or famous"),
            new HumanName("Beryl", 1, Gender.Female, "A gemstone"),
            new HumanName("Bess", 1, Gender.Female, "From the English name Elizabeth"),
            new HumanName("Bet", 1, Gender.Female, "From the English name Elizabeth"),
            new HumanName("Blanche", 1, Gender.Female, "Blonde, white or fair"),
            new HumanName("Bonnie", 1, Gender.Female, "This English girl’s name mean fine, attractive, lovely"),
            new HumanName("Brenda", 1, Gender.Female, "Flaming sword"),
            new HumanName("Brianne", 1, Gender.Female, "The feminine of Brian"),
            new HumanName("Brittany", 1, Gender.Female, "From Britain"),
            new HumanName("Candice", 1, Gender.Female, "From Candace"),
            new HumanName("Cara", 1, Gender.Female, "To beloved"),
            new HumanName("Carissa", 1, Gender.Female, "Tender Touch"),
            new HumanName("Carla", 1, Gender.Female, "Feminine of Charles"),
            new HumanName("Carmel", 1, Gender.Female, "Christian origins"),
            new HumanName("Cass", 1, Gender.Female, "Short for the girl’s name Cassandra"),
            new HumanName("Charis", 1, Gender.Female, "From the Greek name haris to grace"),
            new HumanName("Cherida", 1, Gender.Female, "A mix between Cheryl and Phillida"),
            new HumanName("Cherish", 1, Gender.Female, "To treasure"),
            new HumanName("Courtney", 1, Gender.Female, "Popular in America from the place Courtnay in France"),
            new HumanName("Darlene", 1, Gender.Female, "From the English word Darling"),
            new HumanName("Davida", 1, Gender.Female, "Feminine form of David"),
            new HumanName("Dee", 1, Gender.Female, "Pet ame of Dorothy"),
            new HumanName("Deirdre", 1, Gender.Female, "From Celtic legend Deidre of the Sorrows"),
            new HumanName("Dena", 1, Gender.Female, "Possibly from the name Dean"),
            new HumanName("Dina", 1, Gender.Female, "English veriant of Dinah"),
            new HumanName("Dolly", 1, Gender.Female, "Pet form of Dorothy"),
            new HumanName("Dora", 1, Gender.Female, "From doron meaning a gift"),
            new HumanName("Doris", 1, Gender.Female, "Of the Sea"),
            new HumanName("Ebony", 1, Gender.Female, "English name from black wood"),
            new HumanName("Edna", 1, Gender.Female, "English form of Eithne"),
            new HumanName("Edwina", 1, Gender.Female, "Feminine of Edwin"),
            new HumanName("Effie", 1, Gender.Female, "Pet form of the name Euphemia"),
            new HumanName("Elinor", 1, Gender.Female, "Variation of Eleanor"),
            new HumanName("Elsa", 1, Gender.Female, "Short form of Elizabeth"),
            new HumanName("Enola", 1, Gender.Female, "Origins unknown"),
            new HumanName("Esta", 1, Gender.Female, "Version of Esther"),
            new HumanName("Estelle", 1, Gender.Female, "Means star"),
            new HumanName("Eudora", 1, Gender.Female, "Good Gift"),
            new HumanName("Eugenia", 1, Gender.Female, "From the name Eugenios"),
            new HumanName("Eunice", 1, Gender.Female, "Good victory"),
            new HumanName("Evette", 1, Gender.Female, "Form of Yvette"),
            new HumanName("Fanny", 1, Gender.Female, "Pet form of Frances"),
            new HumanName("Faye", 1, Gender.Female, "Half sister of king Arthur"),
            new HumanName("Flo", 1, Gender.Female, "Comes from the verb to work"),
            new HumanName("Flora", 1, Gender.Female, "Goddess of flowers"),
            new HumanName("Florrie", 1, Gender.Female, "Pet name for Flora"),
            new HumanName("Fran", 1, Gender.Female, "Short for Frances"),
            new HumanName("Frances", 1, Gender.Female, "Female version of Francis"),
            new HumanName("Freda", 1, Gender.Female, "Short name Winfred or Elfreda"),
            new HumanName("Gayle", 1, Gender.Female, "From Abigail"),
            new HumanName("Geraldine", 1, Gender.Female, "Female form of Gerald"),
            new HumanName("Germaine", 1, Gender.Female, "From Germanus"),
            new HumanName("Gertrude", 1, Gender.Female, "From the words ‘gar’ (spear) and ‘prup’ (strength)"),
            new HumanName("Gill", 1, Gender.Female, "Pet form of Gillian"),
            new HumanName("Glynis", 1, Gender.Female, "From Glenys"),
            new HumanName("Gretta", 1, Gender.Female, "English version of the name Greta"),
            new HumanName("Guinevere", 1, Gender.Female, "English girl’s name from Gwenhwfar"),
            new HumanName("Haley", 1, Gender.Female, "Version of Hayley"),
            new HumanName("Hattie", 1, Gender.Female, "From Harriet"),
            new HumanName("Henrietta", 1, Gender.Female, "Female version of Henri"),
            new HumanName("Hettie", 1, Gender.Female, "Pet form of Henrietta"),
            new HumanName("Hilda", 1, Gender.Female, "Means to battle"),
            new HumanName("Hyacinth", 1, Gender.Female, "From mythology"),
            new HumanName("Ida", 1, Gender.Female, "Comes from the verb to work"),
            new HumanName("Iole", 1, Gender.Female, "From mythology"),
            new HumanName("Ivy", 1, Gender.Female, "From the plant Ivy"),
            new HumanName("Jay", 1, Gender.Female, "Pet form of Kay or Dee"),
            new HumanName("Jeane", 1, Gender.Female, "Form of Jean"),
            new HumanName("Judy", 1, Gender.Female, "From the name Judith"),
            new HumanName("Kaley", 1, Gender.Female, "From the name Kayley"),
            new HumanName("Keeley", 1, Gender.Female, "Origin unknown"),
            new HumanName("Kendra", 1, Gender.Female, "From Kendrick"),
            new HumanName("Kerena", 1, Gender.Female, "From the name Keren"),
            new HumanName("Kitty", 1, Gender.Female, "From the name Katherine"),
            new HumanName("Kyla", 1, Gender.Female, "From Kyle"),
            new HumanName("Lana", 1, Gender.Female, "Uncertain origin"),
            new HumanName("Liona", 1, Gender.Female, "From the name Leona"),
            new HumanName("Livia", 1, Gender.Female, "From Olivia"),
            new HumanName("Liza", 1, Gender.Female, "From the name Elizabeth"),
            new HumanName("Lizzie", 1, Gender.Female, "From the name Elizabeth"),
            new HumanName("Loretta", 1, Gender.Female, "English version of Lauretta"),
            new HumanName("Lottie", 1, Gender.Female, "From the girl’s name Charlotte"),
            new HumanName("Lynn", 1, Gender.Female, "From the girl’s name Linda"),
            new HumanName("Madge", 1, Gender.Female, "From the English name Margaret"),
            new HumanName("Malvina", 1, Gender.Female, "A fictitious name"),
            new HumanName("Mara", 1, Gender.Female, "A English name with biblical origins"),
            new HumanName("Marcia", 1, Gender.Female, "Feminine form of Mark"),
            new HumanName("Marice", 1, Gender.Female, "English version og Maris"),
            new HumanName("Maud", 1, Gender.Female, "From the name Matilda"),
            new HumanName("Maura", 1, Gender.Female, "From St Maura"),
            new HumanName("Mavis", 1, Gender.Female, "Means song thrush"),
            new HumanName("May", 1, Gender.Female, "Pet name for Mary and Margaret"),
            new HumanName("Mercy", 1, Gender.Female, "Compassionate or forgiveness"),
            new HumanName("Merle", 1, Gender.Female, "Girl’s name from Meriel"),
            new HumanName("Mildred", 1, Gender.Female, "Means gentle and strong"),
            new HumanName("Millicent", 1, Gender.Female, "From the words meaning labour and strength"),
            new HumanName("Minnie", 1, Gender.Female, "From the name Wilhelmina"),
            new HumanName("Mirabelle", 1, Gender.Female, "Mean wondrous beauty or love"),
            new HumanName("Misty", 1, Gender.Female, "From the word mist/fog"),
            new HumanName("Mona", 1, Gender.Female, "From the name Muadhnait meaning noble"),
            new HumanName("Myra", 1, Gender.Female, "Created by a poet in 17th century"),
            new HumanName("Myrtle", 1, Gender.Female, "From the plant"),
            new HumanName("Nerissa", 1, Gender.Female, "From Shakespeare"),
            new HumanName("Nita", 1, Gender.Female, "Pet form of Anita"),
            new HumanName("Nora", 1, Gender.Female, "Pet form of names like Eleanor"),
            new HumanName("Noreen", 1, Gender.Female, "From the Gaelic name Noirin"),
            new HumanName("Octavia", 1, Gender.Female, "Meaning eighth"),
            new HumanName("Opal", 1, Gender.Female, "From the gemstone"),
            new HumanName("Pandora", 1, Gender.Female, "From mythology"),
            new HumanName("Pansy", 1, Gender.Female, "From the flower"),
            new HumanName("Patience", 1, Gender.Female, "Means virtuous"),
            new HumanName("Pearl", 1, Gender.Female, "From the gemstone"),
            new HumanName("Petra", 1, Gender.Female, "Female version of Peter"),
            new HumanName("Petula", 1, Gender.Female, "Origin unknown"),
            new HumanName("Philomena", 1, Gender.Female, "From a saint"),
            new HumanName("Primrose", 1, Gender.Female, "From the flower"),
            new HumanName("Prudence", 1, Gender.Female, "From the verb prudent"),
            new HumanName("Prunella", 1, Gender.Female, "Plum colour"),
            new HumanName("Queenie", 1, Gender.Female, "Name for the Queen"),
            new HumanName("Raine", 1, Gender.Female, "Origin unknown"),
            new HumanName("Reanna", 1, Gender.Female, "From Deanna"),
            new HumanName("Reenie", 1, Gender.Female, "From the name Rene"),
            new HumanName("Regina", 1, Gender.Female, "Meaning Queen"),
            new HumanName("Rhoda", 1, Gender.Female, "This girl’s name means rose"),
            new HumanName("Rikki", 1, Gender.Female, "Girl’s version of the name Ricky"),
            new HumanName("Rina", 1, Gender.Female, "A pet name for Christina"),
            new HumanName("Rosalind", 1, Gender.Female, "Means tender horse"),
            new HumanName("Rosanne", 1, Gender.Female, "Mix between Rose and Ann"),
            new HumanName("Rowena", 1, Gender.Female, "Origin unknown"),
            new HumanName("Sabella", 1, Gender.Female, "From the girl’s name Isabella"),
            new HumanName("Sapphire", 1, Gender.Female, "From the gemstone"),
            new HumanName("Shannah", 1, Gender.Female, "Origin unknown"),
            new HumanName("Silver", 1, Gender.Female, "From the metal"),
            new HumanName("Sissy", 1, Gender.Female, "From the name Cicely"),
            new HumanName("Tansy", 1, Gender.Female, "From the flower"),
            new HumanName("Teri", 1, Gender.Female, "From the name Terry"),
            new HumanName("Thelma", 1, Gender.Female, "Means wish"),
            new HumanName("Tilda", 1, Gender.Female, "From Matilda"),
            new HumanName("Tori", 1, Gender.Female, "From Victoria"),
            new HumanName("Trina", 1, Gender.Female, "From Katrina"),
            new HumanName("Trudy", 1, Gender.Female, "From Gertrude or Ermintrude"),
            new HumanName("Unity", 1, Gender.Female, "Manes Unity/Quality"),
            new HumanName("Ursa", 1, Gender.Female, "Form of Ursula"),
            new HumanName("Ursula", 1, Gender.Female, "From the Latin name Ursula"),
            new HumanName("Val", 1, Gender.Female, "Short form of Valerie"),
            new HumanName("Valda", 1, Gender.Female, "Inspired by Linda"),
            new HumanName("Valene", 1, Gender.Female, "Australian background"),
            new HumanName("Velma", 1, Gender.Female, "Based on Thelma or Selma"),
            new HumanName("Vere", 1, Gender.Female, "Has a French origin"),
            new HumanName("Verity", 1, Gender.Female, "Means truth"),
            new HumanName("Verona", 1, Gender.Female, "Origin unknown"),
            new HumanName("Vita", 1, Gender.Female, "Pet form of Victoria"),
            new HumanName("Vivian", 1, Gender.Female, "Life"),
            new HumanName("Wanda", 1, Gender.Female, "Origin unknown"),
            new HumanName("Willa", 1, Gender.Female, "From the name William"),
            new HumanName("Wilona", 1, Gender.Female, "From Wilma"),
            new HumanName("Wynne", 1, Gender.Female, "Short from of Winifred"),
            new HumanName("Xenia", 1, Gender.Female, "Hospitality and stranger"),
            new HumanName("Xenthe", 1, Gender.Female, "Means yellow and bright"),
            new HumanName("Yasmin", 1, Gender.Female, "From Jasmin"),
            new HumanName("Yolanda", 1, Gender.Female, "Origin unknown"),
            new HumanName("Zanna", 1, Gender.Female, "From Suzanna"),
            new HumanName("Zelda", 1, Gender.Female, "Origin unknown"),
            new HumanName("Zelene", 1, Gender.Female, "Origin unknown"),
            new HumanName("Zera", 1, Gender.Female, "Means Seeds"),
        });
    }
}